[#176412088] Add io-functions-cgn
pagopa/io-mock pull request #29
Opened 2021-01-26 15:02 UTC by AleDore

This PR is intended to add brand new io-functions-cgn functions to mock images.

2021-01-26 15:23 UTC, BurnedMarshal requested changes

2021-01-26 15:23 UTC, BurnedMarshal commented on docker-compose.yml
> +      dockerfile: io-fixtures/Dockerfile
The base directory should come from `IO_FIXTURES_CONTEXT` context

2021-01-26 15:23 UTC, BurnedMarshal commented on env.io-functions-cgn
> +#TEST_INPS_SERVICE_ENDPOINT=http://webhook.site/INPS-1-OK
Could be removed?

2021-01-26 15:23 UTC, BurnedMarshal commented on env.io-functions-cgn
> +#SERVICES_API_URL=https://api.io.italia.it
Can be removed safely

2021-01-26 15:23 UTC, BurnedMarshal commented on env.io-functions-cgn
> +TEST_FISCAL_CODES=AAAAAA00A00A000B,AAAAAA00A00A000G
How is used this inside `io-fn-cgn`?

2021-01-26 15:30 UTC, AleDore commented on env.io-functions-cgn
> +TEST_FISCAL_CODES=AAAAAA00A00A000B,AAAAAA00A00A000G
I'll remove it

2021-01-26 15:30 UTC, AleDore commented on env.io-functions-cgn
> +#SERVICES_API_URL=https://api.io.italia.it
Removed :)

2021-01-26 15:30 UTC, AleDore commented on env.io-functions-cgn
> +#TEST_INPS_SERVICE_ENDPOINT=http://webhook.site/INPS-1-OK
Yep, I'll remove it

2021-01-26 15:48 UTC, BurnedMarshal reviewed
If the `io-fn-cgn` is called from the `io-backend` maybe some ENVs must be added to the `io-backend` configuration.

2021-01-26 15:50 UTC, AleDore commented
> If the `io-fn-cgn` is called from the `io-backend` maybe some ENVs must be added to the `io-backend` configuration.

Yes, I'm waiting to merge [this](https://github.com/pagopa/io-backend/pull/751) before applying changes on backend env :)

2021-02-19 15:33 UTC, AleDore commented
Can we merge this @BurnedMarshal

2021-02-19 15:33 UTC, AleDore commented
> Can we merge this @BurnedMarshal ?

2021-02-23 15:21 UTC, BurnedMarshal requested changes

2021-02-23 15:21 UTC, BurnedMarshal commented on io-functions-cgn/Dockerfile
> +ARG FUNCTIONS_BONUS_COMMIT_SHA
```suggestion
ARG FUNCTIONS_CGN_COMMIT_SHA
```

2021-02-23 17:36 UTC, BurnedMarshal approved these changes

2021-02-23 17:37 UTC, merged